# Generated by Django 4.0.3 on 2022-03-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat', models.IntegerField()),
                ('name', models.CharField(max_length=23)),
                ('block', models.IntegerField()),
                ('status', models.CharField(max_length=23)),
                ('score', models.IntegerField()),
            ],
        ),
    ]
