# Generated by Django 4.0.3 on 2022-03-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat', models.IntegerField()),
                ('name', models.CharField(max_length=23)),
                ('bloc', models.CharField(max_length=23)),
                ('segregated', models.CharField(max_length=23)),
            ],
        ),
        migrations.AlterField(
            model_name='flat',
            name='block',
            field=models.CharField(max_length=23),
        ),
    ]
