# Generated by Django 4.0.3 on 2022-03-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_manager_alter_flat_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat', models.IntegerField()),
                ('name', models.CharField(max_length=23)),
                ('bloc', models.CharField(max_length=23)),
                ('violations', models.IntegerField()),
            ],
        ),
    ]
